// What a link scraper gets, fetched from a running site rather than reasoned about.
//
//   npm run cards                                  # https://mandate.markets
//   npm run cards -- http://localhost:8788
//   npm run cards -- https://mandate.markets '/s/trade?a=…&k=…'
//
// **The chain this walks is the one that broke twice, and neither break was visible
// from the code** (`notes/2026-09-05-share-cards.md` §8, `2026-09-06-card-image-on-x.md`):
// robots.txt permits the image path → the page carries the tags → `og:image` and
// `twitter:image` are the same URL → that URL is a PNG → its real pixels are the size
// the tags declared. Every link in it is served by us and every one of them can be
// checked without a person pasting anything anywhere.
//
// What it cannot check is the platform: whether X drew the picture is X's business, and
// its card cache keeps an earlier answer for days. This says only that a scraper asking
// today gets everything it needs.

const AGENT = "Twitterbot/1.0";

interface Tags { [k: string]: string }

/** Every `og:*`/`twitter:*` tag in a document, by name. A regex and not a parser: the
 *  page is one file we wrote, the block is generated by `socialTags()`, and the failure
 *  this script exists to catch is a missing or wrong *value*, never exotic markup. */
function socialTags(html: string): Tags {
  const out: Tags = {};
  for (const m of html.matchAll(/<meta\s+(?:property|name)="((?:og|twitter):[^"]+)"\s+content="([^"]*)"/g)) {
    out[m[1]!] = m[2]!.replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;/g, "'");
  }
  return out;
}

/** A PNG's own idea of its size, off the IHDR — the first chunk, always, at byte 16. */
function pngSize(b: Uint8Array): { w: number; h: number } | null {
  const sig = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
  if (b.length < 24 || sig.some((v, i) => b[i] !== v)) return null;
  const v = new DataView(b.buffer, b.byteOffset, b.byteLength);
  return { w: v.getUint32(16), h: v.getUint32(20) };
}

/** Which paths the `*` group forbids. Group selection is the bot's job; what we assert
 *  is the one every scraper we cannot name will read. */
function starDisallows(robots: string): string[] {
  const group = robots.split("\n\n").find((g) => /^User-agent:\s*\*/i.test(g.trim())) ?? "";
  return [...group.matchAll(/^Disallow:\s*(\S+)/gim)].map((m) => m[1]!);
}

let failures = 0;
function check(ok: boolean, label: string, detail = ""): void {
  if (!ok) failures++;
  console.log(`  ${ok ? "ok  " : "FAIL"}  ${label}${detail ? `  — ${detail}` : ""}`);
}

async function get(url: string): Promise<{ res: Response; body: Uint8Array }> {
  const res = await fetch(url, { headers: { "user-agent": AGENT }, redirect: "follow" });
  return { res, body: new Uint8Array(await res.arrayBuffer()) };
}

/** One landing page and the card it points at. `home` is the product card's bytes, so a
 *  signed landing can be held to the thing `tasks/16` §7 asks for: a card that verifies
 *  draws *itself*, and only a card that does not falls back to the product card. That is
 *  the account-card bug of 2026-09-05, which returned 200 and looked fine.
 *
 *  **That test belongs to `/s/…` and to nothing else.** Every other path is *supposed* to
 *  carry the product card: the root does, and so does a referral link (`/?r=CODE`), which
 *  serves the root's head verbatim — same image, and `og:url` left as the bare root on
 *  purpose, so X keeps one ingested card for every code rather than one per code. */
async function landing(origin: string, path: string, home: Uint8Array | null): Promise<Uint8Array | null> {
  const url = new URL(path, origin).href;
  console.log(`\n${url}`);
  const { res, body } = await get(url);
  check(res.ok, `page ${res.status}`);
  if (!res.ok) return null;

  const t = socialTags(new TextDecoder().decode(body));
  check(t["og:image"] !== undefined, "og:image present", t["og:image"] ?? "");
  check(t["twitter:image"] === t["og:image"], "twitter:image is the same URL", t["twitter:image"] ?? "(absent)");
  check(t["twitter:card"] === "summary_large_image", "twitter:card", t["twitter:card"] ?? "(absent)");
  check(t["og:title"] !== undefined && t["og:description"] !== undefined, "title and description", t["og:title"] ?? "");
  if (t["og:image"] === undefined) return null;

  // Declared before fetched: a scraper lays the tile out from these, so they are wrong
  // in somebody else's feed long before anybody here sees the picture.
  const declared = { w: Number(t["og:image:width"]), h: Number(t["og:image:height"]) };
  const img = await get(t["og:image"]);
  check(img.res.ok, `image ${img.res.status}`, `${img.body.length} bytes`);
  check((img.res.headers.get("content-type") ?? "").startsWith("image/png"), "content-type",
    img.res.headers.get("content-type") ?? "(none)");
  const size = pngSize(img.body);
  check(size !== null, "is a PNG");
  if (size) check(size.w === declared.w && size.h === declared.h, "pixels match the declared size",
    `${size.w}x${size.h}, declared ${declared.w}x${declared.h}`);
  if (path.startsWith("/s/")) {
    // Both halves fall back together when a signature does not verify — the landing
    // names `/share/home.png` and the image route draws it — so both are asserted.
    const url = new URL(t["og:image"]!);
    check(url.pathname !== "/share/home.png", "the landing names its own card, not the product card");
    if (home) {
      const same = home.length === img.body.length;
      check(!same, "a signed card draws itself, not the product card",
        same ? "byte-identical to /share/home.png — the signature did not verify" : "");
    }
  }
  return img.body;
}

/** The icon family (`tasks/20` §2.1, §5). Not a card, but the same failure: a path in
 *  the head that answers with the wrong thing is invisible from the code and from the
 *  page, and the last time these were measured every one of them served 258 KB of HTML.
 *  The sizes are asserted from the bytes because a PNG named 180 and drawn at 32 is what
 *  an iOS home screen would show us, once, weeks later. */
async function icons(origin: string): Promise<void> {
  const want: { path: string; type: string; px?: number }[] = [
    { path: "/favicon.svg", type: "image/svg+xml" },
    { path: "/favicon-light.svg", type: "image/svg+xml" },
    { path: "/favicon-dark.svg", type: "image/svg+xml" },
    { path: "/favicon.ico", type: "image/x-icon" },
    { path: "/apple-touch-icon.png", type: "image/png", px: 180 },
    { path: "/icon-512.png", type: "image/png", px: 512 },
  ];
  console.log(`\n${new URL("/favicon.svg", origin).href} and the rest of the icons`);
  for (const w of want) {
    const { res, body } = await get(new URL(w.path, origin).href);
    const type = (res.headers.get("content-type") ?? "").split(";")[0];
    const cache = res.headers.get("cache-control") ?? "";
    const age = Number(/max-age=(\d+)/.exec(cache)?.[1] ?? 0);
    const size = w.px ? pngSize(body) : null;
    const ok = res.ok && type === w.type && age >= 86_400
      && (!w.px || (size?.w === w.px && size.h === w.px))
      && (w.path !== "/favicon.ico" || (body[0] === 0 && body[1] === 0 && body[2] === 1 && body[3] === 0));
    check(ok, w.path, `${res.status} ${type} ${body.length}B max-age=${age}${size ? ` ${size.w}x${size.h}` : ""}`);
  }
}

async function main(): Promise<void> {
  const origin = process.argv[2] ?? "https://mandate.markets";
  const extra = process.argv.slice(3);
  console.log(`origin:  ${origin}\nas:      ${AGENT}`);

  const robots = await get(new URL("/robots.txt", origin).href);
  const disallowed = starDisallows(new TextDecoder().decode(robots.body));
  console.log(`\n${new URL("/robots.txt", origin).href}`);
  check(robots.res.ok, `robots.txt ${robots.res.status}`);
  check(!disallowed.some((p) => "/share/".startsWith(p) || p === "/share/"),
    "the * group may fetch /share/", disallowed.join(" ") || "(nothing disallowed)");

  await icons(origin);

  const home = await get(new URL("/share/home.png", origin).href);
  await landing(origin, "/", null);
  for (const p of extra) await landing(origin, p, home.body);

  console.log(failures === 0 ? "\nall good" : `\n${failures} FAILED`);
  if (failures > 0) process.exitCode = 1;
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
