#!/usr/bin/env python3
"""Regenerate everything derived from the brand mark.

The mark has one source — `design/static/logo#2.svg`, the designer's file — and four
derivatives that are committed beside it: three served favicons, and the `<symbol>` the
two chrome headers and the footer draw. All of them are generated so the path data has
one home; editing a derivative by hand is how they drift.

    python3 design/tools/mark.py && npm run icons && npm run build:web

The rasters (`/favicon.ico`, `/apple-touch-icon.png`, `/icon-512.png`) come from
`src/scripts/icons.ts`, which needs a rasteriser this file does not have — and which
reads the three SVGs written here, so it runs after this and never instead of it.

`tasks/20` §4.4. Run it after the designer sends a new file, never instead of them.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "design/static/logo#2.svg"
FAVICON = ROOT / "design/static/favicon.svg"
FAVICON_LIGHT = ROOT / "design/static/favicon-light.svg"
FAVICON_DARK = ROOT / "design/static/favicon-dark.svg"
PAGE = ROOT / "design/mandate.html"

# The page's two inks. A served SVG gets no cascade from the page, so the favicon has to
# carry its own theme; keep these in step with `--ink` in design/css/tokens.css.
INK_LIGHT = "#16140F"
INK_DARK = "#EDEAE2"

SPRITE_RE = re.compile(
    r'\n<!-- The designer\'s mark \(tasks/20\).*?</symbol></svg>\n', re.S
)


def read_source() -> tuple[str, str]:
    """The source file's viewBox and its inner markup, with the clip id renamed.

    Figma names the clip after its own node number; the page is a shared id space, so
    it gets a name instead.
    """
    svg = SOURCE.read_text()
    view_box = re.search(r'viewBox="([^"]+)"', svg).group(1)
    body = re.sub(r"^.*?<svg[^>]*>", "", svg, flags=re.S)
    body = re.sub(r"</svg>\s*$", "", body, flags=re.S).strip()
    body = re.sub(r"clip0_[0-9_]+", "markclip", body)
    if "currentColor" not in body:
        sys.exit(f"{SOURCE.name} has no currentColor: the ink must follow the theme.")
    return view_box, body


def write_favicon(view_box: str, body: str) -> None:
    """The mark centred in a square viewBox, three times.

    A tab icon is a square slot, and letterboxing a 404x426 drawing inside one is the
    browser's guess rather than ours.

    `favicon.svg` carries its own `prefers-color-scheme`, because a served SVG gets no
    cascade from the page. That is the right rule for the *tab strip*, which follows the
    browser and not us, so it stays the one in the head and the one a scraper gets. The
    two fixed-ink cuts exist for the other half of `tasks/20` §4.5: a reader who picks a
    theme on the page expects the tab to follow their choice rather than their OS, and
    `design/src/theme.ts` swaps the link to one of these when they do.
    """
    width, height = (float(n) for n in view_box.split()[2:])
    pad = (height - width) / 2
    head = (
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'viewBox="{-pad:g} 0 {height:g} {height:g}" '
        f'width="{height:g}" height="{height:g}">'
        f"<!-- Generated by design/tools/mark.py from {SOURCE.name}. Do not edit. -->"
    )
    cuts = {
        FAVICON: (
            f"<style>:root{{color:{INK_LIGHT}}}"
            f"@media(prefers-color-scheme:dark){{:root{{color:{INK_DARK}}}}}</style>"
        ),
        FAVICON_LIGHT: f"<style>:root{{color:{INK_LIGHT}}}</style>",
        FAVICON_DARK: f"<style>:root{{color:{INK_DARK}}}</style>",
    }
    for path, style in cuts.items():
        svg = f"{head}{style}{body}</svg>\n"
        path.write_text(svg)
        print(f"  {path.relative_to(ROOT)}  {len(svg)} bytes")


def write_symbol(view_box: str, body: str) -> None:
    """One <symbol> near the top of the body, drawn three times with <use>."""
    sprite = (
        "\n<!-- The designer's mark (tasks/20), once, for the three places that draw it: the\n"
        "     two chrome headers and the footer. A <symbol> rather than three copies of 2 kB\n"
        "     of path data, and `currentColor` throughout so it follows the theme without a\n"
        "     second rule. Generated by design/tools/mark.py from design/static/logo#2.svg -\n"
        "     edit that and re-run, never this. -->\n"
        '<svg width="0" height="0" aria-hidden="true" style="position:absolute">'
        f'<symbol id="mark-glyph" viewBox="{view_box}">{body}</symbol></svg>\n'
    )
    page = PAGE.read_text()
    page, replaced = SPRITE_RE.subn(sprite, page)
    if replaced != 1:
        sys.exit(f"expected one generated sprite in {PAGE.name}, found {replaced}.")

    glyph = f'<svg class="g" viewBox="{view_box}" aria-hidden="true"><use href="#mark-glyph"/></svg>'
    page, marks = re.subn(r'<svg class="g" viewBox="[^"]*"[^>]*><use href="#mark-glyph"/></svg>',
                          glyph, page)
    if marks != 3:
        sys.exit(f"expected three marks in {PAGE.name}, found {marks}.")

    PAGE.write_text(page)
    print(f"  {PAGE.relative_to(ROOT)}  1 symbol, {marks} marks")


def main() -> None:
    view_box, body = read_source()
    print(f"{SOURCE.relative_to(ROOT)}  viewBox {view_box}")
    write_favicon(view_box, body)
    write_symbol(view_box, body)
    print("now run: npm run icons && npm run build:web")


if __name__ == "__main__":
    main()
