import { verifyMessage } from "viem";
import type { Challenge, Session, WebStore } from "./sessions.ts";

// Sign-in with a wallet signature. No password exists, so none can be stolen.
//
// The signature proves control of an address and **nothing else**. It authorises no
// transaction, and the statement in the message says so in the words the signer will
// actually read — a wallet prompt that does not explain itself trains people to sign
// anything.
//
// The message is SIWE-*shaped* (EIP-4361 field order, so wallets that special-case
// that format render it nicely) but this is not a full EIP-4361 implementation: there
// are no `Resources`, and `Chain ID` is present for rendering only. Nothing here is
// chain-bound, because nothing here touches a chain. What is actually verified is
// exactly two things: the signature recovers to the address that asked for the
// challenge, and the challenge was issued by us, unused, and recent.

export const SESSION_COOKIE = "mandate_session";

export type LoginResult =
  | { ok: true; session: Session }
  | { ok: false; reason: string; kind?: LoginFailure };

/** Why a sign-in failed, when the difference changes what we should tell somebody.
 *
 *  `contract-wallet` is the one that matters. Everything else is "try again". */
export type LoginFailure = "contract-wallet";

const ADDRESS_RE = /^0x[0-9a-fA-F]{40}$/;

/** ERC-6492's trailing magic, on a signature from a wallet that is not deployed yet. */
const ERC6492_SUFFIX = "6492".repeat(16);

/** Is this the 65-byte ECDSA signature an externally-owned account produces, or
 *  something a contract wallet produced that we can never verify?
 *
 *  **The prior question `tasks/11` says must be answered first has an answer, and it
 *  is no.** Every one of the 118 exchange methods in `@nktkas/hyperliquid` 0.33.3
 *  carries `signature: { r, s, v }` with `v` in `{27, 28}` — a 65-byte ECDSA
 *  signature — and there is no field anywhere in the API to carry an ERC-1271
 *  attestation. So a smart-contract wallet cannot approve an agent, cannot place an
 *  order and cannot withdraw. It can only *receive* a deposit, because that is an
 *  ordinary transfer to the bridge and the bridge does not care who sent it.
 *
 *  That settles the shape of the fix. ERC-1271 support at sign-in would be building a
 *  door into a room with no floor: we would let a Safe in, take its deposit, and then
 *  be unable to trade the account it funded. A refusal that says so **before** anyone
 *  deposits is the whole of the correct behaviour.
 *
 *  This is a shape check and not a chain read, deliberately: adding an RPC to the auth
 *  path is a real dependency for a case nobody has reported, and the shape is decisive
 *  in the two cases that matter. An ERC-6492 signature carries a documented magic
 *  suffix; an ERC-1271 attestation is a contract's own opaque bytes and is almost
 *  never exactly 65. A contract wallet that returns exactly 65 bytes still fails
 *  `verifyMessage` and still gets a refusal — just the generic one. */
export function classifySignature(signature: string): "eoa-shaped" | "contract-wallet" {
  const hex = signature.slice(2).toLowerCase();
  if (hex.endsWith(ERC6492_SUFFIX)) return "contract-wallet";
  return hex.length === 130 ? "eoa-shaped" : "contract-wallet";
}

export function isAddress(s: string): boolean {
  return ADDRESS_RE.test(s);
}

/** The exact string the wallet will show. Stored verbatim with the challenge; never
 *  rebuilt at verification time. */
export function buildLoginMessage(o: {
  domain: string;
  address: string;
  uri: string;
  nonce: string;
  issuedAt: string;
}): string {
  return [
    `${o.domain} wants you to sign in with your Ethereum account:`,
    o.address,
    "",
    "Sign in to Mandate. This proves you control this address. It does not authorise " +
    "a transaction and cannot move funds.",
    "",
    `URI: ${o.uri}`,
    "Version: 1",
    "Chain ID: 42161",
    `Nonce: ${o.nonce}`,
    `Issued At: ${o.issuedAt}`,
  ].join("\n");
}

/** Issue a challenge for one address.
 *
 *  The nonce is generated by the store, so the message can only be built once the row
 *  exists. We insert a placeholder-free two-step: reserve the nonce, then rewrite the
 *  message that embeds it. Simpler than threading nonce generation out of the store,
 *  and the row is never visible to a verifier in between because both statements run
 *  before this function returns. */
export function issueChallenge(
  store: WebStore,
  address: string,
  origin: { domain: string; uri: string },
  now = Date.now(),
): Challenge {
  const addr = address.toLowerCase();
  const issuedAt = new Date(now).toISOString();
  const c = store.putChallenge(addr, "", now);
  const message = buildLoginMessage({
    domain: origin.domain,
    address: addr,
    uri: origin.uri,
    nonce: c.nonce,
    issuedAt,
  });
  store.db.prepare("UPDATE login_challenges SET message = ? WHERE nonce = ?").run(message, c.nonce);
  return { ...c, message };
}

/** Verify a signature against a challenge and open a session.
 *
 *  Failure reasons are deliberately coarse in what reaches the client — an attacker
 *  learning "that nonce existed but expired" versus "that nonce was never real" is a
 *  small leak with no upside. The detail stays server-side for the log. */
export async function login(
  store: WebStore,
  input: { address: string; nonce: string; signature: string },
  now = Date.now(),
): Promise<LoginResult> {
  if (!isAddress(input.address)) return { ok: false, reason: "malformed address" };
  if (typeof input.nonce !== "string" || input.nonce.length === 0) {
    return { ok: false, reason: "missing nonce" };
  }
  if (typeof input.signature !== "string" || !/^0x[0-9a-fA-F]+$/.test(input.signature)) {
    return { ok: false, reason: "malformed signature" };
  }

  // Before the challenge is spent: a signature that cannot be an EOA's will not
  // become one on a retry, so burning the challenge would make the second attempt
  // fail for a second, unrelated reason.
  if (classifySignature(input.signature) === "contract-wallet") {
    return {
      ok: false,
      kind: "contract-wallet",
      reason: "signature is not a 65-byte ECDSA signature — a smart-contract wallet",
    };
  }

  const challenge = store.takeChallenge(input.nonce, now);
  if (!challenge) return { ok: false, reason: "challenge unknown, used, or expired" };

  // The challenge is bound to one address at issue time. A signature that recovers to
  // some *other* valid address is still a valid signature — it is just not the one
  // this challenge was for, and accepting it would let anyone log in as anyone.
  if (challenge.address !== input.address.toLowerCase()) {
    return { ok: false, reason: "challenge was issued for a different address" };
  }

  let valid = false;
  try {
    valid = await verifyMessage({
      address: input.address as `0x${string}`,
      message: challenge.message,
      signature: input.signature as `0x${string}`,
    });
  } catch {
    return { ok: false, reason: "signature could not be verified" };
  }
  if (!valid) return { ok: false, reason: "signature does not match this address" };

  return { ok: true, session: store.createSession(challenge.address, now) };
}

/** Read our session cookie out of a request header. Tolerates other cookies and
 *  stray whitespace; refuses anything that is not the shape we issue. */
export function sessionIdFromCookie(header: string | undefined): string | null {
  if (!header) return null;
  for (const part of header.split(";")) {
    const eq = part.indexOf("=");
    if (eq === -1) continue;
    if (part.slice(0, eq).trim() !== SESSION_COOKIE) continue;
    const v = part.slice(eq + 1).trim();
    return /^[0-9a-f]{64}$/.test(v) ? v : null;
  }
  return null;
}

export function sessionCookie(id: string, maxAgeSec: number, secure: boolean): string {
  // SameSite=Lax, not None: nothing about this app is embedded anywhere, and Lax
  // means a cross-site POST cannot carry the session at all — which is the CSRF
  // defence, given every mutating route here is a POST.
  const bits = [
    `${SESSION_COOKIE}=${id}`,
    "Path=/",
    "HttpOnly",
    "SameSite=Lax",
    `Max-Age=${maxAgeSec}`,
  ];
  if (secure) bits.push("Secure");
  return bits.join("; ");
}

export function clearCookie(secure: boolean): string {
  return sessionCookie("", 0, secure);
}
